### ISSUE TITLE
浏览器关闭前向服务器发送一个请求，报告状态

### ISSUE THREAD

**Issue by chenyungcs** [chenyungcs/blog#14]
> 现接到一个需求，收集用户在我司网站的访问行为。

## `unload` 

> 当页面发生跳转、关闭、刷新会先执行`beforeUnload`，待确认后在执行`unload`，所以`beforeUnload`并不能确保一定会关闭

那就在`unload`事件里处理呗

```
window.onunload = function () {
document.getElement('testImg').src = 'http://xxxx.com/collect_page?url=xxxxx';
}
```

设置`<img />`标签地址为接口地址，然后发生请求，然后下班完事了。这么简单？实际情况是：我败了！

balabala....!!!!

网上一顿搜索，都说「同步请求」可解决问题。想象`alert`是同步执行，可阻止进程，那就试一下吧。

```
window.onunload = function () {
    var req = new XMLHttpRequest();
    req.open('GET', 'http://127.0.0.1:7002/login?id=1', false);
    req.send();
}
```

大功告成，下班走人！！

哎！等等好像跟`alert`没半毛钱关系... 继续关注中...    
其实就是跟`alert`有关。只不过只有`IE`可以弹出`alert`。其他浏览器由于安全策略都不允许弹出

![image](https://user-images.githubusercontent.com/10740017/40912301-bfcc03fa-6823-11e8-870a-417df714dea6.png)

不同浏览器、系统间略有差别，暂时参考 #19

**Comment by lionellc** [comment]
safari 基本不支持 onunload 啊

**Comment by chenyungcs** [comment]
末尾有说，不同浏览器存在差别，并给了解决方案的链接



---原始邮件---
发件人: "lionel"<notifications@github.com&gt;
发送时间: 2019年9月19日(星期四) 晚上6:11
收件人: "chenyungcs/blog"<blog@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"丘山"<643288556@qq.com&gt;;
主题: Re: [chenyungcs/blog] 浏览器关闭前向服务器发送一个请求，报告状态 (#14)



safari 基本不支持 onunload 啊
