### ISSUE TITLE
使用scp命令完成自动部署

### ISSUE THREAD

**Issue by chenyungcs** [chenyungcs/blog#17]
> 懒人自有「奇巧淫技」

哈哈，其实也不巧，只是又可以偷懒了。
记得刚毕业，有个Java同事，发布代码一般：

1. 打个`jar包`
2. 复制一段脚本
3. 修改部分参数（路径）
4. 登录到服务器
5. 重启服务

同样的思路，前端要发布到服务器就简单多了：

1. 打个包 'dist/'
2. 在项目下配置下脚本（只需要配置一次就好）
3. 玩去吧

**如下步骤，仅适用于Linux服务器**

### 打包

现在大多数都已经是单页面开发了，且代码都打包到`dist/`这样的目录，总之，第一步，确定你要部署的代码

### 配置脚本

```
#!/bin/bash

host=""
echo "请输入想要部署的环境:"

select env in "Local" "Staging"
do
  case ${env} in
    Local)
    host=root@192.168.0.200
    break;;
    Staging)
    host=root@staging
    break;;
    *)
    echo "输入错误，请重新选择。"
    ;;
   esac
done

echo -e "\033[34m>>>    开始项目部署....\033[0m"
rm -rf dist/ && npm run build && scp -Crq dist/ index.html ${host}:/var/www/html/mall/
```

`.sh`脚本可用`bash`命令执行

```
bash ./bin/deploy.sh
```

`npm`中配置

```
{
    "scripts": {
        "deploy": "bash ./bin/deploy.sh"
    }

}
```
 
### 部署权限怎么控制？

可通过`ssh`去控制，分配服务器的权限。还不会hah，立个 flag
#18 

## 正文`scp`

待更新...

```
scp [-1246BCpqrv] [-c cipher] [-F ssh_config] [-i identity_file]
[-l limit] [-o ssh_option] [-P port] [-S program]
[[user@]host1:]file1 [...] [[user@]host2:]file2
```

## 思考

> 经过一段时间使用，发现，如果网络不佳，发布会比较慢。能不能像git一样，比较差异，有差异的文件才上传

bilinbilin!!!

👏👏👏`rsync`👏👏👏闪亮登场，具体用法请点击[rsync](http://man.linuxde.net/rsync)

**Comment by ghost** [comment]
试试 `rsync`
